disabled_rules:
  - trailing_comma
opt_in_rules:
  - empty_count

excluded:
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

cyclomatic_complexity:
  ignores_case_statements: true

force_cast:
  severity: warning

force_try:
  severity: warning

file_length:
  warning: 500

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 200

line_length:
  warning: 100
  error: 150
